# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04\x64\x65mo\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fResponseMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\x99\x02\n\x0b\x44\x65moService\x12\x38\n\tUnaryCall\x12\x14.demo.RequestMessage\x1a\x15.demo.ResponseMessage\x12\x44\n\x13ServerStreamingCall\x12\x14.demo.RequestMessage\x1a\x15.demo.ResponseMessage0\x01\x12\x44\n\x13\x43lientStreamingCall\x12\x14.demo.RequestMessage\x1a\x15.demo.ResponseMessage(\x01\x12\x44\n\x11\x42idiStreamingCall\x12\x14.demo.RequestMessage\x1a\x15.demo.ResponseMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=23
  _globals['_REQUESTMESSAGE']._serialized_end=56
  _globals['_RESPONSEMESSAGE']._serialized_start=58
  _globals['_RESPONSEMESSAGE']._serialized_end=92
  _globals['_DEMOSERVICE']._serialized_start=95
  _globals['_DEMOSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
